In [1]:
import numpy as np


In [2]:
a = np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
b= np.array([(1.5,2,3), (4,5,6)], dtype=float)

In [5]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [6]:
c=np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]], dtype=float)

In [7]:
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [9]:
e=np.zeros((3,4))

In [10]:
e

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
h=np.ones((2, 3, 4), dtype=np.int16)

In [12]:
h

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [13]:
j=np.arange(10, 25, 5)

In [14]:
j

array([10, 15, 20])

In [15]:
x=np.linspace(0, 2, 9)

In [16]:
x

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [17]:
y=np.full((2, 2), 7)

In [18]:
y

array([[7, 7],
       [7, 7]])

In [19]:
z= np.random.random((2, 2))

In [20]:
z

array([[0.12841327, 0.53606438],
       [0.12748919, 0.55517849]])

In [21]:
 f = np.eye(2)

In [22]:
f

array([[1., 0.],
       [0., 1.]])

In [23]:
a.shape

(3,)

In [25]:
a.shape,a.ndim,a.size


((3,), 1, 3)

In [26]:
b.shape, b.ndim, b.size


((2, 3), 2, 6)

In [27]:
c.shape, c.ndim, c.size


((2, 2, 3), 3, 12)

In [28]:
b.dtype, b.dtype.name

(dtype('float64'), 'float64')

In [29]:
b_int = b.astype(int)
b_int

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
b.dtype, b.dtype.name


(dtype('float64'), 'float64')

In [31]:
a + b


array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [32]:
a - b

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [33]:
b * b

array([[ 2.25,  4.  ,  9.  ],
       [16.  , 25.  , 36.  ]])

In [34]:
b / b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [35]:
np.sqrt(b)

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [36]:
np.sum(b)

np.float64(21.5)

In [37]:
np.min(b)

np.float64(1.5)

In [38]:
np.max(b)

np.float64(6.0)

In [39]:
np.cumsum(b)

array([ 1.5,  3.5,  6.5, 10.5, 15.5, 21.5])

In [40]:
np.mean(b)

np.float64(3.5833333333333335)

In [41]:
np.median(b)

np.float64(3.5)

In [42]:
np.median(b)

np.float64(3.5)

In [43]:
np.std(b)

np.float64(1.5920810978785667)